version: "3.5"

services:
  api1: &api
    image: icarosalgado/rinha-de-backend-2024-q1-graalvm
    hostname: api1
    environment:
      - PORT=8080
      - DB_HOSTNAME=db
    depends_on:
      db:
          condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
    expose:
      - "8080"

  api2:
    <<: *api
    hostname: api2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api2:8080/ping" ]
      timeout: 5s
      interval: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '140MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1